version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - metamix-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    depends_on:
      - backend
    networks:
      - metamix-network

networks:
  metamix-network:
    driver: bridge
